### PR TITLE
chore: replace @ilios/eslint-config with standard

### PR DESCRIPTION
**Pull request by Trott**
`@ilios/eslint-config` is not compatible with ESLint 8.x. Replacing with `standard` so that no one ever has to think about or discuss lint rules again.

### CODE REVIEW

**Comment by Trott** [comment]
I'm going to switch this to semistandard so that you can keep semi-colons.

**Comment by Trott** [comment]
That's a much smaller and more manageable diff. Merge-able?

**Comment by jrjohnson** [comment]
Sorry, commented in Slack and not here. Prettier is our preferred auto-formater. Sample config in [ilios/frontend](https://github.com/ilios/frontend/blob/master/.prettierrc.js)

**Comment by Trott** [comment]
OK, instead of yak-shaving by adding prettier, I'm going to instead duplicate @liios/eslint-config locally but in an ESLint 8-compatible way. If someone wants to standardize all the Ilios repos on a single thing, hey, that works too, and they can replce whatever I do.

**Pull request closed without merging**
